# Data Reprocessing (Pandas)

## Assumptions
- Churn Definition: A user is considered churned if they have a 'Cancellation Confirmation' event in the dataset.
- Time Frame: The analysis will consider user activities in a 7 date window and associate the churn status based on events occurring after this window.


## Cohort Building Logic
- the dataset will identify churned users who have a 'Cancellation Confirmation' event after 2018-10-08 to have at least one week of observation period.
- Non-churned users will match the lookback period of churned users to ensure comparable observation windows using random sampling method (could be further improved).
- Users with insufficient data (less than 7 days of activity, n = 7) will be excluded from the analysis to maintain data integrity.
- The cohort aims to provide a forward predictive view of user behavior leading up to churn events.
- 55 inactive users observed in the random sampled non-churned cohort, there are two options to handle them, each represents a different strategy on apply the model in production:
    1. Keep them in the dataset, as they represent a cross-sectional users segment that may churn, this cross-sectional segment contains users who are inactive, and their inactivity may lead to customer retension in near future. **[Risky]** the dataset may not reflect the real percentage of inactive users in the population, which may bias the model.
    2. Exclude them from the dataset to focus the model on active user behavior, which may provide clearer insights into churn predictors among engaged users and their near future churn behavior. **[Safer]** the dataset will better reflect the real percentage of inactive users in the population, which may reduce the bias of the model.


## Attributes To Be Included in Data Preprocessing and Engineering

* Churn
* Since Registration
* Gender
* Paid Category
* Page event counts
* Device
* Location
* Song stats
* Artist stats
* Session Stats
* Page Stats

### Libraries

In [1]:
import pandas as pd

pd.set_option("display.max_rows", 1000)
pd.set_option("display.max_columns", 200)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

### Load Data

In [2]:
se_data = pd.read_json("../Data/mini_sparkify_event_data.json",lines=True)
print(se_data.userId.nunique())
se_data = se_data[se_data['userId']!=""]
print(se_data.userId.nunique())
se_data['ts'] = pd.to_datetime(se_data['ts'], unit='ms')
se_data['registration'] = pd.to_datetime(se_data['registration'], unit='ms')

226
225

### Cohort Building

In [3]:
churn_user_date_df = se_data[se_data['page'] == 'Cancellation Confirmation'][['userId', 'ts']].rename(columns={'ts':'cancel_date'})
churn_user_date_df['churn'] = True
churn_user_date_df['include'] = churn_user_date_df['cancel_date'].dt.date >= pd.to_datetime('2018-10-08').date()
churn_user_date_df['start_date'] = None
churn_user_date_df.loc[churn_user_date_df['include'], 'start_date'] = (churn_user_date_df.loc[churn_user_date_df['include'], 'cancel_date'] - pd.Timedelta(days=7)).dt.floor('d')
exclude_churn_users = churn_user_date_df[~churn_user_date_df['include']]['userId'].unique()
churn_user_date_df['end_date'] = churn_user_date_df['cancel_date']
print(churn_user_date_df.shape)

(52, 6)

In [4]:
churn_user_date_df[churn_user_date_df['include']].userId.nunique()

45

In [5]:
se_users = se_data[['userId']].drop_duplicates()
se_users = se_users.merge(churn_user_date_df,how='left')
se_users['include'] = se_users['include'].fillna(True)
se_users['churn'] = se_users['churn'].fillna(False)
start_dates = churn_user_date_df[churn_user_date_df['include']].start_date.tolist()
mask = (se_users['include'])&(se_users.start_date.isna())
n_start_dates_to_assign = se_users[mask].shape[0]
# random sample with replacement from start_dates to assign to users without churn date
se_users.loc[mask, 'start_date'] = pd.Series(start_dates).sample(n=n_start_dates_to_assign, replace=True, random_state=42).values
se_users['start_date'] = pd.to_datetime(se_users['start_date'])
se_users['end_date'] = se_users['start_date'] + pd.Timedelta(days=7)
se_users[se_users['include']].groupby('churn').describe()

/var/folders/0c/_lvyy05j49g_r0hzzfhr03tm0000gn/T/ipykernel_75429/2704280262.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  se_users['include'] = se_users['include'].fillna(True)
/var/folders/0c/_lvyy05j49g_r0hzzfhr03tm0000gn/T/ipykernel_75429/2704280262.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  se_users['churn'] = se_users['churn'].fillna(False)

      cancel_date                                                      \
            count                           mean                  min
churn
False           0                            NaT                  NaT
True           45  2018-10-30 23:33:16.511111168  2018-10-08 21:10:46

                                                                      \
                       25%                  50%                  75%
churn
False                  NaT                  NaT                  NaT
True   2018-10-17 07:39:32  2018-10-30 04:59:03  2018-11-12 19:40:08

                           start_date                                 \
                       max      count                           mean
churn
False                  NaT        173  2018-10-22 20:06:56.184971008
True   2018-11-29 11:45:09         45            2018-10-23 10:40:00

                                                                      \
                       min                  25%                  50%
churn
False  2018-10-01 00:00:00  2018-10-10 00:00:00  2018-10-20 00:00:00
True   2018-10-01 00:00:00  2018-10-10 00:00:00  2018-10-23 00:00:00

                                                end_date  \
                       75%                  max    count
churn
False  2018-11-07 00:00:00  2018-11-22 00:00:00      173
True   2018-11-05 00:00:00  2018-11-22 00:00:00       45

                                                           \
                                mean                  min
churn
False  2018-10-29 20:06:56.184971008  2018-10-08 00:00:00
True             2018-10-30 10:40:00  2018-10-08 00:00:00

                                                                      \
                       25%                  50%                  75%
churn
False  2018-10-17 00:00:00  2018-10-27 00:00:00  2018-11-14 00:00:00
True   2018-10-17 00:00:00  2018-10-30 00:00:00  2018-11-12 00:00:00


                       max
churn
False  2018-11-29 00:00:00
True   2018-11-29 00:00:00

In [6]:
print(f"Total records before filtering: {se_data.shape[0]}")
se_data_sub_activity = se_data[se_data['userId']!=""].merge(se_users[se_users['include']], on='userId', how='inner')
se_data_sub_activity = se_data_sub_activity[(se_data_sub_activity['ts'] >= se_data_sub_activity['start_date']) & (se_data_sub_activity['ts'] <= se_data_sub_activity['end_date'])]
print(f"Total records after filtering: {se_data_sub_activity.shape[0]}")

Total records before filtering: 278154
Total records after filtering: 39624

In [7]:
se_data_sub_activity.userId.nunique()

163

In [8]:
se_data_sub_activity.drop(columns=['cancel_date', 'include', 'start_date', 'end_date']).groupby(['userId', 'churn']).nunique().reset_index().groupby('churn').describe()

          ts                                                             \
       count        mean         std  min    25%    50%     75%     max
churn
False  126.0  214.904762  242.894559  1.0   49.0  135.5  252.75  1156.0
True    37.0  336.081081  321.281668  2.0  143.0  222.0  399.00  1150.0

      sessionId                                                 page  \
          count      mean       std  min  25%  50%  75%   max  count
churn
False     126.0  2.587302  2.067926  1.0  1.0  2.0  3.0  12.0  126.0
True       37.0  3.486486  2.155376  1.0  2.0  3.0  5.0   8.0   37.0

                                                        auth                 \
           mean       std  min  25%   50%   75%   max  count mean  std  min
churn
False  8.547619  3.270736  1.0  6.0   9.0  11.0  16.0  126.0  1.0  0.0  1.0
True   9.864865  3.392493  1.0  9.0  11.0  12.0  16.0   37.0  1.0  0.0  1.0

                          method                                               \
       25%  50%  75%  max  count      mean       std  min  25%  50%  75%  max
churn
False  1.0  1.0  1.0  1.0  126.0  1.984127  0.125483  1.0  2.0  2.0  2.0  2.0
True   1.0  1.0  1.0  1.0   37.0  1.972973  0.164399  1.0  2.0  2.0  2.0  2.0

      status                                               level            \
       count      mean       std  min  25%  50%  75%  max  count      mean
churn
False  126.0  2.150794  0.420808  1.0  2.0  2.0  2.0  3.0  126.0  1.134921
True    37.0  2.000000  0.333333  1.0  2.0  2.0  2.0  3.0   37.0  1.189189

                                         itemInSession              \
            std  min  25%  50%  75%  max         count        mean
churn
False  0.343003  1.0  1.0  1.0  1.0  2.0         126.0  145.261905
True   0.397061  1.0  1.0  1.0  1.0  2.0          37.0  190.081081

                                                    location                 \
              std  min   25%    50%     75%     max    count mean  std  min
churn
False  157.067434  1.0  37.0   90.0  203.25  1080.0    126.0  1.0  0.0  1.0
True   178.372485  2.0  69.0  135.0  297.00   868.0     37.0  1.0  0.0  1.0

                          userAgent                                     \
       25%  50%  75%  max     count mean  std  min  25%  50%  75%  max
churn
False  1.0  1.0  1.0  1.0     126.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0
True   1.0  1.0  1.0  1.0      37.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

      lastName                                    firstName                 \
         count mean  std  min  25%  50%  75%  max     count mean  std  min
churn
False    126.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0     126.0  1.0  0.0  1.0
True      37.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0      37.0  1.0  0.0  1.0

                          registration                                     \
       25%  50%  75%  max        count mean  std  min  25%  50%  75%  max
churn
False  1.0  1.0  1.0  1.0        126.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0
True   1.0  1.0  1.0  1.0         37.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

      gender                                    artist              \
       count mean  std  min  25%  50%  75%  max  count        mean
churn
False  126.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  126.0  156.142857
True    37.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0   37.0  236.216216

                                                      song              \
              std  min    25%    50%     75%    max  count        mean
churn
False  165.044126  0.0   34.5  100.5  192.25  766.0  126.0  171.230159
True   214.501636  2.0  113.0  174.0  288.00  739.0   37.0  263.324324

                                                   length              \
              std  min    25%    50%    75%    max  count        mean
churn
False  192.637075  0.0   34.5  102.5  204.0  912.0  126.0  167.880952
True   254.460983  2.0  117.0  179.0  306.0  884.0   37.0  256.702703


              std  min    25%    50%    75%    max
churn
False  185.508840  0.0   34.5  101.5  202.0  870.0
True   243.583988  2.0  116.0  179.0  305.0  851.0

In [9]:
se_users['has_activity'] = se_users['userId'].isin(se_data_sub_activity['userId'])
se_users['has_activity'].value_counts()

has_activity
True     163
False     62
Name: count, dtype: int64

### Data Preprocessing & Feature Engineering

**Label**
* Churn ✅

**persona**
* Gender ✅
* Location ✅

**Account**
* Since Registration ✅
* Paid Category ✅

**Activities / Behavioral**
* Device
* Page event counts
* Session event counts

**Preferences**
* Song stats
* Artist stats

#### Label & Cohort Main DataFrame

In [10]:
se_data_in_scope_user = se_data[se_data['userId'].isin(se_users[se_users['include']]['userId'])].copy()

In [11]:
se_cohort_df = se_users[se_users['include']].drop(columns=['include']).copy()
se_cohort_df.shape

(218, 6)

#### Persona

In [12]:
unique_ids = se_data['userId'].unique()
excl_ids = se_users[~se_users['include']]['userId'].unique().tolist()
print(f"total userIds: {len(unique_ids)}")
print(f"empty userIds: {len([uid for uid in unique_ids if uid == ''])}")
print(f"excluded churned userIds: {len(excl_ids)}")
print(f"final cohort userIds: {len(unique_ids) - len([uid for uid in unique_ids if uid == '']) - len(excl_ids)}")
# total userId: 226; 
# minus 1 empty userId '', 225 remaining;
# exclude 7 churned users who cancelled before 2018-10-08, final cohort userIds: 218

total userIds: 225
empty userIds: 0
excluded churned userIds: 7
final cohort userIds: 218

In [13]:
persona_cols = ['userId','gender', 'location', 'registration']
se_data[(se_data['userId'] != '') & (se_data['userId'].isin(se_users[se_users['include']]['userId']))][persona_cols]\
    .drop_duplicates()\
    .groupby('userId').nunique().reset_index().describe()
# all users have unique profile info

       gender  location  registration
count   218.0     218.0         218.0
mean      1.0       1.0           1.0
std       0.0       0.0           0.0
min       1.0       1.0           1.0
25%       1.0       1.0           1.0
50%       1.0       1.0           1.0
75%       1.0       1.0           1.0
max       1.0       1.0           1.0

In [14]:
se_persona = se_users[se_users['include']][['userId','end_date']].merge(
    se_data[(se_data['userId'] != '') & (se_data['userId'].isin(se_users[se_users['include']]['userId']))][persona_cols]\
    .drop_duplicates(), how='inner', on='userId'
)
se_persona['day_since_reg'] = (se_persona['end_date'] - se_persona['registration']).dt.days
print(f"persona df shape: {se_persona.shape}")
se_persona[['city','state']] = se_persona['location'].str.split(',', expand=True)
se_persona['city'] = se_persona['city'].str.strip().str.title()
se_persona['state'] = se_persona['state'].str.strip().str.upper()
se_persona = se_persona[['userId','gender','city','state','day_since_reg']]\
    .rename(columns={'gender':'psn_gender','city':'psn_city','state':'psn_state','day_since_reg':'acct_day_since_reg'})

persona df shape: (218, 6)

In [15]:
# Feature engineering
se_persona['psn_multi_city'] = se_persona['psn_city'].str.contains('-')
se_persona['psn_multi_state'] = se_persona['psn_state'].str.contains('-')

In [16]:
se_persona
# location definitions require further cleaning:
# - some cities have multiple names separated by '-', some separated by '--'
# - some states have multiple abbreviations separated by '-'
# - by default multi_state should have multi_city records, but there are some exceptions

,userId,psn_gender,psn_city,psn_state,acct_day_since_reg,psn_multi_city,psn_multi_state
0,30,M,Bakersfield,CA,34,False,False
1,9,M,Boston-Cambridge-Newton,MA-NH,31,True,True
2,74,F,Tallahassee,FL,40,False,False
3,54,F,Spokane-Spokane Valley,WA,109,True,False
4,4,M,Baltimore-Columbia-Towson,MD,48,True,False
5,101,M,Denver-Aurora-Lakewood,CO,53,True,False
6,78,F,Mcallen-Edinburg-Mission,TX,16,True,False
7,88,F,Columbus,GA-AL,63,False,True
8,95,F,Phoenix-Mesa-Scottsdale,AZ,33,True,False
9,25,F,Tampa-St. Petersburg-Clearwater,FL,65,True,False
10,142,M,New York-Newark-Jersey City,NY-NJ-PA,12,True,True
11,13,F,Philadelphia-Camden-Wilmington,PA-NJ-DE-MD,78,True,True
12,45,F,Atlanta-Sandy Springs-Roswell,GA,41,True,False
13,39,F,Los Angeles-Long Beach-Anaheim,CA,120,True,False
14,87,M,Quincy,IL-MO,58,False,True
15,28,F,New Philadelphia-Dover,OH,44,True,False
16,131,M,Kingsport-Bristol-Bristol,TN-VA,74,True,True
17,126,M,New York-Newark-Jersey City,NY-NJ-PA,33,True,True
18,146,M,Myrtle Beach-Conway-North Myrtle Beach,SC-NC,38,True,True
19,59,M,Boulder,CO,16,False,False
20,15,M,Morgantown,WV,50,False,False
21,36,F,Minneapolis-St. Paul-Bloomington,MN-WI,62,True,True
22,120,F,Oklahoma City,OK,81,False,False
23,92,F,Boston-Cambridge-Newton,MA-NH,69,True,True
24,33,M,Hartford-West Hartford-East Hartford,CT,137,True,False
25,51,M,Lexington-Fayette,KY,19,True,False
26,27,M,Hartford-West Hartford-East Hartford,CT,79,True,False
27,143,F,Virginia Beach-Norfolk-Newport News,VA-NC,61,True,True
28,140,F,Louisville/Jefferson County,KY-IN,30,False,True
29,6,M,Houston-The Woodlands-Sugar Land,TX,240,True,False
30,124,F,Vineland-Bridgeton,NJ,124,True,False
31,141,F,Price,UT,49,False,False
32,93,M,Allentown-Bethlehem-Easton,PA-NJ,59,True,True
33,81,M,Philadelphia-Camden-Wilmington,PA-NJ-DE-MD,84,True,True
34,40,F,San Antonio-New Braunfels,TX,50,True,False
35,94,F,Omaha-Council Bluffs,NE-IA,103,True,True
36,113,F,Charlotte-Concord-Gastonia,NC-SC,107,True,True
37,98,M,Houston-The Woodlands-Sugar Land,TX,29,True,False
38,137,M,New York-Newark-Jersey City,NY-NJ-PA,100,True,True
39,65,M,Concord,NH,40,False,False
40,53,M,Jackson,MS,52,False,False
41,42,F,Danville,VA,53,False,False
42,115,F,Los Angeles-Long Beach-Anaheim,CA,27,True,False
43,38,M,Pittsburgh,PA,37,False,False
44,58,M,Selma,AL,25,False,False
45,77,F,Gainesville,FL,22,False,False
46,52,F,Atlanta-Sandy Springs-Roswell,GA,87,True,False
47,29,M,Los Angeles-Long Beach-Anaheim,CA,59,True,False
48,70,M,Jackson,MS,144,False,False
49,61,M,San Francisco-Oakland-Hayward,CA,29,True,False
50,46,F,Los Angeles-Long Beach-Anaheim,CA,38,True,False
51,35,F,Washington-Arlington-Alexandria,DC-VA-MD-WV,51,True,True
52,132,F,Denver-Aurora-Lakewood,CO,27,True,False
53,127,F,Dallas-Fort Worth-Arlington,TX,36,True,False
54,136,F,Charlotte-Concord-Gastonia,NC-SC,38,True,True
55,80,F,Sacramento--Roseville--Arden-Arcade,CA,16,True,False
56,110,M,Chicago-Naperville-Elgin,IL-IN-WI,26,True,True
57,129,M,Flint,MI,16,False,False
58,121,M,Oxnard-Thousand Oaks-Ventura,CA,131,True,False
59,82,F,Kansas City,MO-KS,27,False,True
60,100,M,Dallas-Fort Worth-Arlington,TX,48,True,False
61,117,F,Buffalo-Cheektowaga-Niagara Falls,NY,39,True,False
62,85,M,Los Angeles-Long Beach-Anaheim,CA,64,True,False
63,118,F,New York-Newark-Jersey City,NY-NJ-PA,52,True,True
64,105,M,Indianapolis-Carmel-Anderson,IN,28,True,False
65,96,F,Atlantic City-Hammonton,NJ,29,True,False
66,20,F,Miami-Fort Lauderdale-West Palm Beach,FL,76,True,False
67,55,M,Las Vegas-Henderson-Paradise,NV,42,True,False
68,3,M,Bozeman,MT,80,False,False
69,12,F,Los Angeles-Long Beach-Anaheim,CA,72,True,False
70,41,F,Manchester-Nashua,NH,90,True,False
71,73,F,Albany-Schenectady-Troy,NY,49,True,False
72,17,F,Philadelphia-Camden-Wilmington,PA-NJ-DE-MD,12,True,True
73,86,M,Jacksonville,FL,90,False,False
74,7,M,Seattle-Tacoma-Bellevue,WA,51,True,False
75,67,M,Sacramento--Roseville--Arden-Arcade,CA,100,True,False
76,32,M,Phoenix-Mesa-Scottsdale,AZ,20,True,False
77,5,M,Phoenix-Mesa-Scottsdale,AZ,21,True,False
78,106,F,Los Angeles-Long Beach-Anaheim,CA,39,True,False
79,114,M,Las Vegas-Henderson-Paradise,NV,32,True,False
80,69,F,Milwaukee-Waukesha-West Allis,WI,62,True,False
81,99,F,New Haven-Milford,CT,87,True,False
82,16,F,Winston-Salem,NC,51,True,False
83,49,M,Napa,CA,82,False,False
84,50,F,Dubuque,IA,33,False,False
85,24,M,Troy,AL,63,False,False
86,103,F,New York-Newark-Jersey City,NY-NJ-PA,41,True,True
87,102,M,New York-Newark-Jersey City,NY-NJ-PA,60,True,True
88,122,F,Memphis,TN-MS-AR,52,False,True
89,75,F,Buffalo-Cheektowaga-Niagara Falls,NY,32,True,False
90,135,F,Las Vegas-Henderson-Paradise,NV,82,True,False
91,128,M,Fairbanks,AK,58,False,False
92,111,F,Detroit-Warren-Dearborn,MI,64,True,False
93,112,M,Muncie,IN,55,False,False
94,145,F,Pittsburgh,PA,57,False,False
95,66,F,Los Angeles-Long Beach-Anaheim,CA,89,True,False
96,83,M,Anchorage,AK,74,False,False
97,44,F,Bridgeport-Stamford-Norwalk,CT,38,True,False
98,11,F,Providence-Warwick,RI-MA,111,True,True
99,91,M,New Haven-Milford,CT,89,True,False
100,37,M,Austin-Round Rock,TX,88,True,False
101,90,M,Seattle-Tacoma-Bellevue,WA,86,True,False
102,104,F,Billings,MT,80,False,False
103,138,M,New York-Newark-Jersey City,NY-NJ-PA,24,True,True
104,148,M,Miami-Fort Lauderdale-West Palm Beach,FL,27,True,False
105,107,F,Pontiac,IL,76,False,False
106,97,F,Riverside-San Bernardino-Ontario,CA,65,True,False
107,109,F,St. Louis,MO-IL,72,False,True
108,134,M,Indianapolis-Carmel-Anderson,IN,37,True,False
109,10,M,Laurel,MS,55,False,False
110,2,F,Raleigh,NC,24,False,False
111,144,M,Montgomery,AL,56,False,False
112,76,M,Los Angeles-Long Beach-Anaheim,CA,19,True,False
113,119,F,Charlotte-Concord-Gastonia,NC-SC,149,True,True
114,89,M,Atlanta-Sandy Springs-Roswell,GA,42,True,False
115,14,M,Syracuse,NY,81,False,False
116,62,M,Houston-The Woodlands-Sugar Land,TX,122,True,False
117,19,F,Dayton,OH,28,False,False
118,150,M,Phoenix-Mesa-Scottsdale,AZ,76,True,False
119,68,F,Cincinnati,OH-KY-IN,65,False,True
120,147,M,Charlotte-Concord-Gastonia,NC-SC,43,True,True
121,8,F,St. Louis,MO-IL,70,False,True
122,56,M,Alexandria,LA,65,False,False
123,34,M,Deltona-Daytona Beach-Ormond Beach,FL,78,True,False
124,60,M,Phoenix-Mesa-Scottsdale,AZ,69,True,False
125,125,M,Corpus Christi,TX,71,False,False
126,47,M,Columbus,GA-AL,90,False,True
127,133,M,San Diego-Carlsbad,CA,70,True,False
128,26,M,Stockton-Lodi,CA,49,True,False
129,43,F,Boston-Cambridge-Newton,MA-NH,59,True,True
130,57,M,Truckee-Grass Valley,CA,64,True,False
131,149,M,Dallas-Fort Worth-Arlington,TX,31,True,False
132,64,M,Dallas-Fort Worth-Arlington,TX,25,True,False
133,21,M,Kankakee,IL,33,False,False
134,71,M,Tallahassee,FL,22,False,False
135,108,F,Washington-Arlington-Alexandria,DC-VA-MD-WV,56,True,True
136,79,M,Philadelphia-Camden-Wilmington,PA-NJ-DE-MD,70,True,True
137,123,M,Tampa-St. Petersburg-Clearwater,FL,56,True,False
138,116,F,Providence-Warwick,RI-MA,56,True,True
139,152,M,Los Angeles-Long Beach-Anaheim,CA,-7,True,False
140,63,F,Duluth,MN-WI,67,False,True
141,139,M,Los Angeles-Long Beach-Anaheim,CA,82,True,False
142,23,F,Chicago-Naperville-Elgin,IL-IN-WI,113,True,True
143,154,F,New York-Newark-Jersey City,NY-NJ-PA,15,True,True
144,155,F,Boston-Cambridge-Newton,MA-NH,-13,True,True
145,72,F,Port St. Lucie,FL,146,False,False
146,151,M,Washington-Arlington-Alexandria,DC-VA-MD-WV,12,True,True
147,153,M,Greensboro-High Point,NC,25,True,False
148,22,F,Cincinnati,OH-KY-IN,30,False,True
149,84,F,Virginia Beach-Norfolk-Newport News,VA-NC,29,True,True
150,156,M,Scranton--Wilkes-Barre--Hazleton,PA,-46,True,False
151,100009,M,San Francisco-Oakland-Hayward,CA,37,True,False
152,100022,F,Houston-The Woodlands-Sugar Land,TX,47,True,False
153,100025,F,New York-Newark-Jersey City,NY-NJ-PA,88,True,True
154,100005,M,Monroe,LA,84,False,False
155,100016,M,St. Louis,MO-IL,24,False,True
156,100015,F,North Wilkesboro,NC,67,False,False
157,100007,F,Little Rock-North Little Rock-Conway,AR,114,True,False
158,100013,F,Cleveland-Elyria,OH,43,True,False
159,100004,F,Syracuse,NY,127,False,False
160,100012,M,Chicago-Naperville-Elgin,IL-IN-WI,42,True,True
161,100023,M,Greenville-Anderson-Mauldin,SC,32,True,False
162,100018,M,Dallas-Fort Worth-Arlington,TX,71,True,False
163,100010,F,Bridgeport-Stamford-Norwalk,CT,26,True,False
164,100002,F,Santa Maria-Santa Barbara,CA,129,True,False
165,100003,F,Miami-Fort Lauderdale-West Palm Beach,FL,22,True,False
166,100008,F,Los Angeles-Long Beach-Anaheim,CA,32,True,False
167,100014,M,New York-Newark-Jersey City,NY-NJ-PA,84,True,True
168,100021,M,Dallas-Fort Worth-Arlington,TX,64,True,False
169,100017,M,Birmingham-Hoover,AL,78,True,False
170,200014,M,Hagerstown-Martinsburg,MD-WV,85,True,True
171,200019,M,Los Angeles-Long Beach-Anaheim,CA,37,True,False
172,200002,M,Chicago-Naperville-Elgin,IL-IN-WI,53,True,True
173,200023,F,New York-Newark-Jersey City,NY-NJ-PA,25,True,True
174,200001,M,Washington-Arlington-Alexandria,DC-VA-MD-WV,15,True,True
175,200020,M,Orlando-Kissimmee-Sanford,FL,75,True,False
176,200022,M,St. Louis,MO-IL,98,False,True
177,200006,F,Los Angeles-Long Beach-Anaheim,CA,37,True,False
178,200011,M,St. Louis,MO-IL,109,False,True
179,200010,F,Logan,UT-ID,56,False,True
180,200015,M,San Diego-Carlsbad,CA,87,True,False
181,200004,M,Jacksonville,NC,39,False,False
182,200021,F,Detroit-Warren-Dearborn,MI,70,True,False
183,200017,M,New York-Newark-Jersey City,NY-NJ-PA,60,True,True
184,200008,F,Charlotte-Concord-Gastonia,NC-SC,104,True,True
185,200024,M,London,KY,28,False,False
186,200003,F,Chicago-Naperville-Elgin,IL-IN-WI,104,True,True
187,200018,M,Philadelphia-Camden-Wilmington,PA-NJ-DE-MD,48,True,True
188,200009,M,Sterling,IL,32,False,False
189,200025,M,Salinas,CA,88,False,False
190,200016,F,Baltimore-Columbia-Towson,MD,55,True,False
191,200007,F,New York-Newark-Jersey City,NY-NJ-PA,14,True,True
192,200005,M,Greenville-Anderson-Mauldin,SC,87,True,False
193,200012,M,Portland-Vancouver-Hillsboro,OR-WA,57,True,True
194,300001,F,Colorado Springs,CO,187,False,False
195,300017,F,Ionia,MI,43,False,False
196,300015,M,San Antonio-New Braunfels,TX,156,True,False
197,300011,F,New York-Newark-Jersey City,NY-NJ-PA,31,True,True
198,300008,F,Cookeville,TN,45,False,False
199,300023,F,Boston-Cambridge-Newton,MA-NH,111,True,True
200,300021,F,Wilson,NC,58,False,False
201,300009,F,St. Louis,MO-IL,56,False,True
202,300025,M,San Jose-Sunnyvale-Santa Clara,CA,65,True,False
203,300002,F,Truckee-Grass Valley,CA,92,True,False
204,300012,M,Miami-Fort Lauderdale-West Palm Beach,FL,104,True,False
205,300005,F,Roanoke,VA,155,False,False
206,300010,M,Dallas-Fort Worth-Arlington,TX,70,True,False
207,300014,M,San Diego-Carlsbad,CA,69,True,False
208,300016,M,Minneapolis-St. Paul-Bloomington,MN-WI,69,True,True
209,300019,M,Los Angeles-Long Beach-Anaheim,CA,51,True,False
210,300020,F,Atlanta-Sandy Springs-Roswell,GA,51,True,False
211,300022,M,London,KY,92,False,False
212,300013,M,Charlotte-Concord-Gastonia,NC-SC,78,True,True
213,300018,M,Chicago-Naperville-Elgin,IL-IN-WI,63,True,True
214,300006,M,New Haven-Milford,CT,53,True,False
215,300003,M,Portland-Vancouver-Hillsboro,OR-WA,113,True,True
216,300004,F,Los Angeles-Long Beach-Anaheim,CA,62,True,False
217,300024,F,Phoenix-Mesa-Scottsdale,AZ,52,True,False

#### Account

In [17]:
se_data_in_scope_user.groupby('userId')['level'].nunique().reset_index().describe()

            level
count  218.000000
mean     1.619266
std      0.486685
min      1.000000
25%      1.000000
50%      2.000000
75%      2.000000
max      2.000000

In [18]:
act_before_end_df = se_data_in_scope_user.merge(se_users,how='left',on='userId').query('end_date > ts')
se_last_level = (
    act_before_end_df[~act_before_end_df['page'].str.lower().str.contains('cancel')]
    .sort_values(['userId', 'ts'])
    .groupby('userId')['level']
    .agg(last_level='last', multiple_levels=lambda x: x.nunique() > 1)
    .reset_index()
)
print(se_last_level.shape)
# there are only 202 user IDs in the filtered data period, the rest 16 user does not have level info before end_date, interpolate nearest datapoint from the dataset, and multiple_level as false as there was no level change

se_last_level

(202, 3)

     userId last_level  multiple_levels
0        10       paid            False
1       100       free             True
2    100002       paid            False
3    100003       free            False
4    100004       free            False
5    100005       free            False
6    100007       paid            False
7    100008       paid            False
8    100009       free             True
9    100010       free            False
10   100012       free             True
11   100013       paid             True
12   100014       paid            False
13   100015       paid             True
14   100016       paid            False
15   100018       free             True
16   100021       free            False
17   100022       free            False
18   100023       paid             True
19   100025       free             True
20      101       paid             True
21      102       free            False
22      103       paid             True
23      104       free            False
24      105       paid             True
25      106       paid             True
26      107       free            False
27      108       paid             True
28      109       paid             True
29       11       free             True
30      110       free            False
31      111       paid             True
32      112       free            False
33      113       paid             True
34      114       free            False
35      115       paid             True
36      117       free            False
37      118       paid             True
38      119       free            False
39       12       paid             True
40      120       paid            False
41      121       paid             True
42      122       free            False
43      124       paid            False
44      126       paid             True
45      127       paid            False
46      128       paid             True
47      129       paid             True
48       13       free            False
49      131       paid             True
50      132       paid             True
51      133       free            False
52      134       free            False
53      135       free            False
54      136       paid             True
55      137       free            False
56      138       free            False
57      139       paid             True
58      140       paid             True
59      141       paid             True
60      142       paid             True
61      143       free            False
62      144       free            False
63      145       paid            False
64      146       free            False
65      147       free            False
66      148       free            False
67      149       free            False
68       15       paid            False
69      150       free            False
70      153       paid             True
71      154       free            False
72       16       paid             True
73       17       paid             True
74       19       paid            False
75       20       paid             True
76   200001       free            False
77   200002       paid             True
78   200003       free             True
79   200004       paid            False
80   200005       free            False
81   200006       free            False
82   200008       paid             True
83   200009       free             True
84   200010       free            False
85   200011       free             True
86   200014       free            False
87   200015       free            False
88   200016       free            False
89   200017       paid             True
90   200018       free            False
91   200019       free             True
92   200020       free             True
93   200021       paid             True
94   200022       free            False
95   200023       free             True
96   200024       paid             True
97   200025       free             True
98       23       free            False
99       24       free             True
100      25       free             True
101      26       free            False
102      27       free            False
103      28       paid             True
104      29       paid             True
105       3       paid            False
106      30       free             True
107  300001       paid             True
108  300002       paid             True
109  300003       free            False
110  300004       paid             True
111  300005       paid             True
112  300006       free            False
113  300008       paid            False
114  300009       paid             True
115  300010       free            False
116  300011       paid             True
117  300012       paid             True
118  300013       paid            False
119  300014       paid             True
120  300015       paid             True
121  300016       paid             True
122  300017       paid            False
123  300018       paid             True
124  300019       paid             True
125  300020       paid            False
126  300021       paid             True
127  300022       paid            False
128  300023       paid            False
129  300024       paid            False
130  300025       paid             True
131      32       free            False
132      33       paid            False
133      34       free            False
134      35       paid             True
135      36       free            False
136      37       paid             True
137      38       free             True
138      39       paid             True
139       4       paid             True
140      40       paid             True
141      41       paid            False
142      42       paid             True
143      43       free            False
144      44       paid             True
145      45       free            False
146      46       paid             True
147      47       free            False
148      49       paid            False
149       5       free            False
150      50       free            False
151      51       paid            False
152      52       paid             True
153      53       paid             True
154      54       paid             True
155      55       free            False
156      56       paid             True
157      57       free            False
158      58       paid             True
159      59       paid             True
160       6       paid             True
161      60       paid             True
162      61       free             True
163      62       paid            False
164      63       free            False
165      65       paid             True
166      66       free            False
167      67       free            False
168      68       free            False
169      69       paid             True
170       7       free            False
171      70       paid             True
172      71       free            False
173      72       free            False
174      73       paid             True
175      74       free             True
176      75       paid            False
177      76       free            False
178      77       free             True
179      78       free            False
180      79       paid             True
181       8       free            False
182      80       free            False
183      81       paid             True
184      82       free            False
185      83       free            False
186      85       free             True
187      86       free            False
188      87       free            False
189      88       paid             True
190      89       free            False
191       9       paid             True
192      90       free            False
193      91       paid             True
194      92       paid             True
195      93       free            False
196      94       free            False
197      95       free             True
198      96       paid            False
199      97       paid             True
200      98       paid             True
201      99       free            False

In [19]:
rest_level_df = se_data_in_scope_user[~se_data_in_scope_user['userId'].isin(se_last_level.userId)][['userId','ts','level']] \
    .merge(se_users[['userId','end_date']],how='left',on='userId').copy()
rest_level_df['time_diff'] = (rest_level_df['end_date'] - rest_level_df['ts']).abs()
rest_level_nearest = rest_level_df.sort_values(['userId','time_diff']).groupby('userId').first().reset_index()[['userId','level']].rename(columns={'level':'last_level'})
rest_level_nearest['multiple_levels'] = False
rest_level_nearest

    userId last_level  multiple_levels
0   100017       free            False
1      116       free            False
2      123       free            False
3      125       free            False
4       14       paid            False
5      151       paid            False
6      152       free            False
7      155       free            False
8      156       free            False
9        2       paid            False
10  200007       paid            False
11  200012       free            False
12      21       paid            False
13      22       free            False
14      64       free            False
15      84       free            False

In [20]:
se_last_level = pd.concat([se_last_level, rest_level_nearest], ignore_index=True)
se_last_level = se_last_level.rename(columns={'last_level':'acct_last_level','multiple_levels':'acct_multiple_levels'})
se_last_level.shape

(218, 3)

#### Activities / Behavioral

In [21]:
se_page = se_data_sub_activity.loc[~se_data_sub_activity['page'].str.lower().str.contains('cancel'), ['userId','page']]\
    .assign(page=lambda x: 'act_page_' + x['page'].str.replace(' ', '_').str.lower())\
    .pivot_table(index='userId', columns='page', aggfunc='size', fill_value=0)\
    .reset_index()
se_page_agg = se_data_sub_activity.loc[~se_data_sub_activity['page'].str.lower().str.contains('cancel'), ['userId','page']]\
    .groupby('userId')['page'].agg(['count','nunique']).reset_index().rename(columns={'count':'total_page_visits', 'nunique':'unique_page_types'})
se_page = se_page.merge(se_page_agg, how='left', on='userId')
print(se_page.shape)
se_page = se_cohort_df[['userId']].merge(se_page, how='left', on='userId').fillna(0)
print(se_page.shape)
for col in se_page.columns[1:]:
    se_page[col] = se_page[col].astype(int)
se_page

(163, 20)
(218, 20)

,userId,act_page_about,act_page_add_friend,act_page_add_to_playlist,act_page_downgrade,act_page_error,act_page_help,act_page_home,act_page_logout,act_page_nextsong,act_page_roll_advert,act_page_save_settings,act_page_settings,act_page_submit_downgrade,act_page_submit_upgrade,act_page_thumbs_down,act_page_thumbs_up,act_page_upgrade,total_page_visits,unique_page_types
0,30,1,3,5,0,0,1,9,4,221,18,0,4,0,0,2,9,4,281,12
1,9,0,4,3,2,1,2,6,1,158,6,0,0,1,1,1,10,2,198,14
2,74,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1
3,54,2,5,11,13,0,4,21,5,526,0,1,5,0,0,8,36,0,637,12
4,4,1,14,12,4,2,6,17,3,437,0,0,2,0,0,4,24,0,526,12
5,101,1,9,37,15,0,3,47,15,917,1,2,7,0,0,11,48,0,1113,13
6,78,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,88,1,2,8,4,0,2,7,1,230,0,1,2,0,0,3,12,0,273,12
8,95,0,0,0,0,1,0,1,2,64,4,0,0,0,0,1,3,1,77,8
9,25,0,6,15,4,0,1,26,6,495,5,0,2,1,0,4,25,0,590,12
10,142,1,4,18,7,3,3,19,6,576,2,2,6,0,0,3,27,0,677,14
11,13,1,2,11,0,0,0,7,2,166,11,0,1,0,0,0,11,1,213,10
12,45,0,0,0,0,0,0,4,0,17,0,0,0,0,0,0,1,0,22,3
13,39,3,20,28,8,2,6,39,10,970,4,0,6,0,1,15,48,1,1161,15
14,87,0,14,7,0,0,5,25,9,220,22,0,5,0,0,3,8,1,319,11
15,28,2,10,27,10,0,1,33,12,896,0,0,1,0,0,16,51,0,1059,11
16,131,0,2,1,1,0,2,1,0,60,0,0,0,0,0,0,4,0,71,7
17,126,1,1,4,5,0,1,12,6,156,0,1,2,0,0,3,10,0,202,12
18,146,0,0,1,0,0,0,1,0,30,0,0,0,0,0,1,1,0,34,5
19,59,0,0,1,2,0,0,4,1,64,0,0,1,0,1,2,2,1,79,10
20,15,0,5,10,1,0,1,9,1,191,0,1,1,0,0,1,6,0,227,11
21,36,1,5,3,0,0,2,6,2,101,11,0,0,0,0,3,4,1,139,11
22,120,0,4,7,5,0,0,7,4,355,0,1,4,0,0,2,18,0,407,10
23,92,2,19,34,11,1,3,33,15,947,0,0,7,0,0,18,44,0,1134,12
24,33,1,2,3,4,0,1,11,3,191,0,1,1,0,0,3,14,0,235,12
25,51,0,4,21,10,0,6,23,6,851,0,1,4,0,0,10,40,0,976,11
26,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,143,0,0,0,0,0,0,3,0,17,2,0,0,0,0,0,1,0,23,4
28,140,1,10,21,6,1,5,32,11,732,9,1,4,0,1,11,27,1,873,16
29,6,0,0,3,0,0,0,3,0,144,0,0,0,0,0,1,8,0,159,5
30,124,1,1,3,1,0,0,11,4,224,0,0,0,0,0,4,6,0,255,9
31,141,0,2,2,1,0,0,3,1,73,0,0,0,0,0,1,2,0,85,8
32,93,0,0,0,0,0,0,0,0,11,1,0,0,0,0,0,1,0,13,3
33,81,0,0,0,0,0,0,1,1,7,0,0,0,0,0,0,1,0,10,4
34,40,2,0,3,0,0,1,5,0,65,0,0,2,0,1,0,4,1,84,9
35,94,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
36,113,0,0,3,1,1,0,4,0,123,0,0,1,0,0,1,7,0,141,8
37,98,0,0,7,2,1,2,11,4,162,1,0,2,0,1,1,7,1,202,13
38,137,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
39,65,0,6,8,1,0,0,9,1,207,0,0,1,0,0,4,11,0,248,9
40,53,3,10,12,3,1,4,15,5,579,0,0,1,0,0,4,26,0,663,12
41,42,0,1,5,1,1,3,13,4,220,0,0,4,0,0,2,10,0,264,11
42,115,2,12,29,15,2,6,27,7,900,8,2,6,0,1,13,49,1,1080,16
43,38,0,0,0,0,0,1,5,2,45,1,0,0,0,0,0,1,1,56,7
44,58,0,12,31,10,0,8,34,13,969,0,1,3,0,0,14,57,0,1152,11
45,77,3,1,2,3,0,0,17,3,203,0,0,1,1,0,1,6,0,241,11
46,52,2,21,7,1,0,0,10,4,298,1,0,1,0,0,1,11,0,357,11
47,29,0,1,7,0,0,4,6,3,182,0,0,4,0,0,2,13,0,222,9
48,70,0,1,5,2,0,1,11,6,176,0,1,1,0,0,1,14,0,219,11
49,61,0,9,13,5,1,3,22,7,499,11,0,1,1,0,3,26,1,602,14
50,46,1,5,8,1,0,0,9,3,156,5,0,0,0,1,3,7,1,200,12
51,35,3,5,12,5,0,4,13,5,341,1,0,0,0,0,3,12,0,404,11
52,132,0,0,1,1,0,2,3,1,64,0,0,0,0,0,2,7,0,81,8
53,127,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
54,136,0,14,22,10,0,2,20,3,654,0,1,4,0,0,3,37,0,770,11
55,80,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
56,110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
57,129,0,2,2,3,0,2,5,2,122,1,0,1,0,0,3,5,0,148,11
58,121,1,15,11,2,0,2,32,14,408,3,3,9,0,1,5,17,2,525,15
59,82,1,2,5,0,0,0,11,4,136,6,0,0,0,0,3,7,1,176,10
60,100,0,0,0,0,0,2,5,4,35,1,0,0,0,0,0,2,0,49,6
61,117,0,0,1,0,0,0,2,1,21,0,0,0,0,0,0,0,0,25,4
62,85,1,5,12,4,0,2,18,5,311,3,0,0,1,0,5,15,0,382,12
63,118,0,6,1,2,0,1,4,1,121,0,1,1,0,0,1,8,0,147,11
64,105,0,0,0,3,0,0,5,2,69,0,1,2,0,0,3,6,0,91,8
65,96,0,4,3,1,0,0,7,1,140,0,0,1,0,0,5,6,0,168,9
66,20,0,1,1,1,0,1,6,1,86,0,0,1,0,0,1,9,0,108,10
67,55,0,0,0,0,0,0,1,2,14,0,0,0,0,0,0,0,0,17,3
68,3,1,1,3,0,0,1,7,3,154,0,0,0,0,0,3,10,0,183,9
69,12,1,8,9,2,1,1,20,5,317,6,1,3,0,1,4,18,2,399,16
70,41,0,0,3,1,0,0,3,0,89,0,1,1,0,0,0,4,0,102,7
71,73,1,7,5,0,0,1,7,2,168,0,1,2,0,0,3,5,0,202,11
72,17,1,10,21,10,0,4,23,11,664,0,0,4,0,1,10,28,1,788,13
73,86,0,1,0,0,0,0,2,0,16,0,0,0,0,0,0,0,0,19,3
74,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
75,67,0,0,3,0,0,0,3,1,89,9,0,0,0,0,0,2,0,107,6
76,32,0,0,4,0,0,0,1,1,38,2,0,0,0,0,0,5,0,51,6
77,5,0,0,2,0,0,0,1,0,29,4,0,0,0,0,0,2,1,39,6
78,106,0,10,12,1,0,4,9,1,261,0,0,0,0,0,2,10,0,310,9
79,114,0,1,2,0,0,1,5,3,33,1,0,0,0,0,0,4,1,51,9
80,69,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
81,99,0,0,1,0,0,0,4,2,31,3,0,1,0,0,0,0,0,42,6
82,16,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
83,49,0,2,2,3,0,1,1,0,36,0,0,0,0,0,1,3,0,49,8
84,50,0,0,1,0,2,0,7,2,76,4,1,1,0,0,2,4,0,100,10
85,24,1,2,1,0,0,0,2,1,64,0,0,0,0,0,0,4,0,75,7
86,103,0,10,12,9,0,1,14,5,372,0,0,1,0,0,4,23,0,451,10
87,102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
88,122,0,0,0,0,0,0,2,0,6,1,0,0,0,0,0,0,0,9,3
89,75,0,0,3,0,0,0,1,0,49,0,0,0,0,0,0,2,0,55,4
90,135,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
91,128,0,10,3,0,1,3,13,5,164,0,0,1,0,0,2,6,0,208,10
92,111,0,6,2,2,0,1,5,2,138,0,0,0,0,0,2,7,0,165,9
93,112,0,1,1,0,0,0,2,0,28,1,0,0,0,0,0,0,0,33,5
94,145,0,5,1,0,0,0,3,2,92,0,0,1,0,0,0,4,0,108,7
95,66,0,1,2,0,0,1,7,2,108,10,0,0,0,0,0,4,1,136,9
96,83,0,0,0,0,0,1,3,0,40,2,0,0,0,0,1,2,0,49,6
97,44,2,7,8,1,0,5,10,3,361,0,1,4,0,0,1,24,0,427,12
98,11,0,1,0,0,0,0,5,2,56,5,1,1,0,0,0,5,2,78,9
99,91,0,2,3,1,0,1,8,2,209,0,0,0,0,0,1,11,0,238,9
100,37,0,8,9,1,0,0,14,4,308,0,0,3,0,0,0,21,0,368,8
101,90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
102,104,1,0,4,0,0,0,7,0,100,7,0,0,0,0,0,3,0,122,6
103,138,1,5,7,0,0,2,5,2,182,12,1,1,0,0,1,12,0,231,12
104,148,0,0,2,0,0,3,11,3,208,14,0,1,0,0,0,12,2,256,9
105,107,0,0,0,0,0,0,1,0,15,0,0,0,0,0,0,1,0,17,3
106,97,3,13,18,3,0,4,20,10,549,1,0,1,0,0,5,24,0,651,12
107,109,0,3,5,4,0,2,5,3,175,0,0,1,0,0,3,8,0,209,10
108,134,0,0,1,0,0,0,1,0,10,1,0,0,0,0,1,0,0,14,5
109,10,0,1,1,3,0,0,2,2,90,0,0,1,0,0,0,3,0,103,8
110,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
111,144,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
112,76,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
113,119,0,1,4,0,1,0,7,1,61,3,0,0,0,0,0,2,2,82,9
114,89,0,0,1,0,0,0,0,0,12,2,0,0,0,0,0,1,0,16,4
115,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
116,62,0,4,5,0,2,2,7,0,169,0,0,1,0,0,6,12,0,208,9
117,19,2,2,7,0,0,0,7,5,124,0,0,1,0,0,1,3,0,152,9
118,150,0,1,5,0,0,1,4,0,79,7,1,1,0,0,0,5,1,105,10
119,68,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
120,147,0,10,1,0,0,1,4,1,63,2,0,0,0,0,0,8,0,90,8
121,8,0,5,2,0,0,0,9,2,117,10,0,0,0,0,0,9,1,155,8
122,56,1,5,1,8,0,1,11,4,102,0,0,1,0,0,0,4,0,138,10
123,34,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
124,60,1,1,8,6,1,1,9,2,201,1,0,0,0,0,3,18,0,252,12
125,125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
126,47,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,3,1
127,133,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
128,26,0,1,3,0,0,1,6,2,125,5,0,1,0,0,1,6,0,151,10
129,43,0,0,1,0,0,0,2,2,24,3,0,0,0,0,0,1,1,34,7
130,57,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
131,149,0,3,1,0,0,1,3,1,32,1,0,1,0,0,0,1,0,44,9
132,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
133,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
134,71,0,0,0,0,0,0,1,0,9,2,0,0,0,0,0,1,0,13,4
135,108,1,12,8,1,0,4,14,4,297,0,1,3,0,0,0,11,0,356,11
136,79,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
137,123,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
138,116,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
139,152,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
140,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
141,139,1,6,8,6,1,1,14,4,274,0,0,0,0,0,5,16,0,336,11
142,23,0,0,3,0,0,0,1,0,42,8,0,0,0,0,0,2,0,56,5
143,154,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
144,155,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
145,72,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
146,151,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
147,153,1,5,9,2,0,2,9,4,178,0,0,0,0,0,1,10,0,221,10
148,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
149,84,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
150,156,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
151,100009,0,2,2,2,0,3,6,4,145,17,0,0,1,0,2,11,1,196,12
152,100022,0,1,1,0,0,2,8,4,122,25,0,0,0,0,5,6,2,176,10
153,100025,1,3,8,5,0,3,20,7,295,24,3,5,1,0,5,14,1,395,15
154,100005,0,0,0,0,0,0,2,1,19,4,0,0,0,0,1,0,0,27,5
155,100016,0,0,0,0,0,0,0,0,16,1,0,0,0,0,0,1,0,18,3
156,100015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
157,100007,0,0,1,0,0,0,1,0,11,1,0,0,0,0,0,2,0,16,5
158,100013,0,6,8,4,0,1,9,3,249,3,1,2,0,0,7,11,0,304,12
159,100004,0,5,0,0,0,1,2,1,69,11,0,1,0,0,0,5,0,95,8
160,100012,1,1,6,0,0,0,7,3,129,15,0,0,0,0,3,7,0,172,9
161,100023,0,7,6,8,0,3,16,5,309,2,0,1,0,0,1,8,0,366,11
162,100018,0,0,0,0,0,0,1,1,18,3,0,0,0,0,1,1,0,25,6
163,100010,0,2,1,0,0,0,2,0,44,8,0,0,0,0,0,2,1,60,7
164,100002,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
165,100003,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,2,1
166,100008,0,0,2,2,0,0,0,0,16,1,0,0,0,0,0,0,0,21,4
167,100014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
168,100021,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
169,100017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
170,200014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
171,200019,1,0,6,1,0,0,5,2,78,3,0,0,1,0,0,3,1,101,10
172,200002,0,0,0,0,0,0,2,0,21,0,0,0,0,0,0,1,0,24,3
173,200023,0,3,5,0,0,0,10,6,170,11,0,0,0,0,3,5,2,215,9
174,200001,0,0,2,0,0,0,5,0,70,3,1,1,0,0,0,7,1,90,8
175,200020,0,0,2,0,0,1,7,1,119,7,0,1,0,0,4,4,0,146,9
176,200022,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
177,200006,0,0,0,0,0,0,0,1,10,1,0,0,0,0,1,1,0,14,5
178,200011,0,0,5,7,0,3,9,4,202,3,0,2,1,0,8,9,0,253,11
179,200010,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
180,200015,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
181,200004,0,2,11,3,0,0,5,2,194,0,0,1,0,0,3,12,0,233,9
182,200021,2,4,4,5,0,0,18,4,254,1,1,3,0,0,7,13,0,316,12
183,200017,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
184,200008,5,10,12,5,1,2,22,6,508,0,0,1,0,0,16,18,0,606,12
185,200024,0,5,2,2,0,0,9,5,220,6,1,2,0,1,5,12,3,273,13
186,200003,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
187,200018,1,6,6,0,0,0,4,1,136,13,0,0,0,0,4,7,3,181,10
188,200009,0,8,13,5,0,6,21,8,449,4,1,4,1,0,21,19,0,560,13
189,200025,0,0,0,0,0,0,3,1,34,2,0,0,0,0,3,2,0,45,6
190,200016,0,0,1,0,0,0,2,1,11,0,0,0,0,0,0,3,0,18,5
191,200007,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
192,200005,0,1,0,0,0,0,2,2,16,1,0,0,0,0,0,0,1,23,6
193,200012,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
194,300001,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
195,300017,0,4,9,2,0,3,13,6,321,2,0,2,0,0,7,26,0,395,11
196,300015,0,1,5,0,2,1,10,2,150,0,0,2,0,0,2,15,0,190,10
197,300011,4,17,24,4,0,7,29,5,711,0,0,3,0,0,2,72,0,878,11
198,300008,0,0,4,1,0,1,4,1,105,0,0,0,0,0,1,7,0,124,8
199,300023,1,11,15,2,1,1,15,4,466,0,1,2,0,0,4,36,0,559,13
200,300021,1,12,19,1,2,1,20,7,537,0,0,2,0,0,3,34,0,639,12
201,300009,0,11,15,4,0,3,14,8,527,0,0,1,0,0,4,47,0,634,10
202,300025,0,1,4,1,0,0,6,3,123,0,0,0,0,0,3,13,0,154,8
203,300002,0,7,11,2,0,4,10,3,298,3,0,1,1,1,1,36,1,379,14
204,300012,0,0,0,0,0,0,2,0,20,2,0,0,0,1,1,1,2,29,7
205,300005,0,1,0,0,0,0,3,0,25,0,0,0,0,0,1,3,0,33,5
206,300010,0,0,0,0,0,0,1,0,10,0,0,0,0,0,0,2,0,13,3
207,300014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
208,300016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
209,300019,1,12,15,0,0,4,14,2,495,0,0,0,0,0,4,54,0,601,9
210,300020,0,0,0,0,0,1,0,0,33,0,0,0,0,0,0,1,0,35,3
211,300022,0,1,0,0,0,0,1,0,15,0,0,0,0,0,0,1,0,18,4
212,300013,0,1,1,0,0,1,2,0,65,0,0,0,0,0,0,5,0,75,6
213,300018,0,7,3,0,0,1,3,0,52,0,0,0,0,0,0,2,0,68,6
214,300006,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
215,300003,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
216,300004,0,0,0,0,0,3,2,1,59,8,0,1,0,1,1,3,1,80,10
217,300024,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [22]:
se_session = se_data_sub_activity[['userId','sessionId']]\
    .groupby('userId')['sessionId']\
    .agg(['nunique','mean'])\
    .reset_index()\
    .rename(columns={'nunique':'session_count', 'mean':'session_avg_pages'})
print(se_session.shape)
se_session = se_session.merge(se_cohort_df[['userId']], how='right', on='userId').fillna(0)
print(se_session.shape)
se_session

(163, 3)
(218, 3)

     userId  session_count  session_avg_pages
0        30            5.0        1353.619217
1         9            3.0        1323.772727
2        74            1.0        1173.000000
3        54            7.0        1693.499215
4         4            2.0        1746.277567
5       101            4.0         658.261456
6        78            0.0           0.000000
7        88            2.0        1682.666667
8        95            2.0        1324.714286
9        25            3.0        1542.688136
10      142            3.0         520.262925
11       13            4.0         871.727700
12       45            1.0         631.000000
13       39           12.0         702.811370
14       87            8.0         884.934169
15       28            6.0        1459.217186
16      131            2.0         559.661972
17      126            3.0        1277.351485
18      146            1.0         395.000000
19       59            1.0         455.000000
20       15            3.0        1899.599119
21       36            5.0         535.956835
22      120            2.0         502.164619
23       92           12.0        1883.174603
24       33            2.0         918.259574
25       51            6.0         747.556352
26       27            0.0           0.000000
27      143            1.0         552.000000
28      140            8.0         585.819015
29        6            2.0        1662.257862
30      124            3.0        2008.701961
31      141            1.0         649.000000
32       93            1.0        1621.000000
33       81            1.0        1768.000000
34       40            2.0         803.142857
35       94            0.0           0.000000
36      113            2.0        1717.638298
37       98            2.0        1136.504950
38      137            0.0           0.000000
39       65            2.0        1317.830645
40       53            4.0        1903.770739
41       42            4.0        1850.829545
42      115            1.0         316.000000
43       38            3.0         950.607143
44       58            5.0         966.440104
45       77            2.0         416.199170
46       52            1.0        1573.000000
47       29            4.0        1786.567568
48       70            2.0        1629.698630
49       61            3.0         565.151163
50       46            4.0        1361.310000
51       35            5.0        1530.868812
52      132            2.0         632.000000
53      127            0.0           0.000000
54      136            5.0        1037.736364
55       80            0.0           0.000000
56      110            0.0           0.000000
57      129            2.0         641.533784
58      121            7.0         809.996190
59       82            3.0         614.579545
60      100            5.0        1698.510204
61      117            1.0         702.000000
62       85            6.0         717.212042
63      118            4.0        1856.625850
64      105            1.0         464.000000
65       96            4.0         765.940476
66       20            3.0        2118.416667
67       55            2.0        1009.411765
68        3            2.0        1002.524590
69       12            3.0         911.977444
70       41            1.0        1189.000000
71       73            2.0         987.995050
72       17            5.0         654.343909
73       86            1.0         651.000000
74        7            0.0           0.000000
75       67            2.0         537.822430
76       32            2.0         280.000000
77        5            2.0         484.000000
78      106            3.0        1298.122581
79      114            2.0         716.607843
80       69            0.0           0.000000
81       99            3.0         506.333333
82       16            0.0           0.000000
83       49            2.0        1008.938776
84       50            2.0         653.730000
85       24            1.0        1358.000000
86      103            2.0        1163.527716
87      102            0.0           0.000000
88      122            1.0         691.000000
89       75            1.0         467.000000
90      135            0.0           0.000000
91      128            2.0         909.538462
92      111            1.0        1568.000000
93      112            1.0         580.000000
94      145            4.0         809.935185
95       66            3.0         980.169118
96       83            3.0         164.755102
97       44            1.0         758.000000
98       11            2.0        1664.846154
99       91            1.0        1223.000000
100      37            3.0        2067.725543
101      90            0.0           0.000000
102     104            2.0         644.000000
103     138            3.0         933.112554
104     148            2.0         793.500000
105     107            1.0        1800.000000
106      97            5.0        1557.783410
107     109            2.0        1229.057416
108     134            1.0         573.000000
109      10            2.0        1950.786408
110       2            0.0           0.000000
111     144            0.0           0.000000
112      76            0.0           0.000000
113     119            1.0         633.000000
114      89            1.0         178.000000
115      14            0.0           0.000000
116      62            1.0        1763.000000
117      19            1.0         159.000000
118     150            2.0         411.800000
119      68            0.0           0.000000
120     147            1.0         888.000000
121       8            1.0         234.000000
122      56            3.0        2216.159420
123      34            0.0           0.000000
124      60            5.0        2081.734127
125     125            0.0           0.000000
126      47            1.0          46.000000
127     133            0.0           0.000000
128      26            2.0        1169.139073
129      43            1.0         989.000000
130      57            0.0           0.000000
131     149            1.0         148.000000
132      64            0.0           0.000000
133      21            0.0           0.000000
134      71            1.0         170.000000
135     108            1.0        1896.000000
136      79            0.0           0.000000
137     123            0.0           0.000000
138     116            0.0           0.000000
139     152            0.0           0.000000
140      63            0.0           0.000000
141     139            2.0        1807.705357
142      23            1.0         166.000000
143     154            0.0           0.000000
144     155            0.0           0.000000
145      72            0.0           0.000000
146     151            0.0           0.000000
147     153            5.0        2206.384615
148      22            0.0           0.000000
149      84            0.0           0.000000
150     156            0.0           0.000000
151  100009            2.0         131.556122
152  100022            6.0         178.823864
153  100025            2.0         122.681013
154  100005            1.0          75.000000
155  100016            1.0          32.000000
156  100015            0.0           0.000000
157  100007            1.0         192.000000
158  100013            4.0         147.671053
159  100004            3.0          93.768421
160  100012            3.0         130.755814
161  100023            8.0          87.269755
162  100018            1.0          89.000000
163  100010            1.0         118.000000
164  100002            0.0           0.000000
165  100003            1.0           3.000000
166  100008            1.0         117.000000
167  100014            0.0           0.000000
168  100021            0.0           0.000000
169  100017            0.0           0.000000
170  200014            0.0           0.000000
171  200019            2.0         156.277228
172  200002            1.0         174.000000
173  200023            9.0         151.609302
174  200001            3.0         101.155556
175  200020            7.0         326.732877
176  200022            0.0           0.000000
177  200006            2.0         137.142857
178  200011            3.0         226.442688
179  200010            0.0           0.000000
180  200015            0.0           0.000000
181  200004            3.0         247.467811
182  200021            4.0         242.917722
183  200017            0.0           0.000000
184  200008            4.0         330.851485
185  200024            4.0         189.893773
186  200003            0.0           0.000000
187  200018            2.0         217.204420
188  200009            6.0         238.987500
189  200025            2.0         155.000000
190  200016            1.0         297.000000
191  200007            0.0           0.000000
192  200005            1.0         239.000000
193  200012            0.0           0.000000
194  300001            0.0           0.000000
195  300017            6.0         246.020253
196  300015            3.0         363.547368
197  300011           10.0         264.215262
198  300008            3.0          90.088710
199  300023            4.0         152.957066
200  300021            5.0         377.574335
201  300009            2.0          82.350158
202  300025            3.0         365.909091
203  300002            3.0         219.063325
204  300012            1.0          74.000000
205  300005            1.0         226.000000
206  300010            1.0         225.000000
207  300014            0.0           0.000000
208  300016            0.0           0.000000
209  300019            2.0         195.492512
210  300020            1.0         257.000000
211  300022            1.0         345.000000
212  300013            1.0         205.000000
213  300018            3.0         279.220588
214  300006            0.0           0.000000
215  300003            0.0           0.000000
216  300004            1.0          27.000000
217  300024            0.0           0.000000

In [23]:
se_days_active = se_data_sub_activity[['userId','ts']]\
    .assign(activity_day=lambda x: x['ts'].dt.floor('d'))\
    .groupby('userId')['activity_day'].nunique().reset_index().rename(columns={'activity_day':'act_days_active'})
print(se_days_active.shape)
se_days_active = se_days_active.merge(se_cohort_df[['userId']], how='right', on='userId').fillna(0)
print(se_days_active.shape)
se_days_active

(163, 2)
(218, 2)

     userId  act_days_active
0        30              4.0
1         9              4.0
2        74              1.0
3        54              6.0
4         4              2.0
5       101              6.0
6        78              0.0
7        88              2.0
8        95              1.0
9        25              3.0
10      142              4.0
11       13              4.0
12       45              1.0
13       39              7.0
14       87              5.0
15       28              4.0
16      131              1.0
17      126              2.0
18      146              1.0
19       59              1.0
20       15              3.0
21       36              3.0
22      120              3.0
23       92              7.0
24       33              2.0
25       51              5.0
26       27              0.0
27      143              1.0
28      140              7.0
29        6              1.0
30      124              3.0
31      141              1.0
32       93              1.0
33       81              1.0
34       40              2.0
35       94              0.0
36      113              2.0
37       98              2.0
38      137              0.0
39       65              1.0
40       53              5.0
41       42              3.0
42      115              3.0
43       38              3.0
44       58              5.0
45       77              2.0
46       52              2.0
47       29              3.0
48       70              2.0
49       61              4.0
50       46              4.0
51       35              4.0
52      132              2.0
53      127              0.0
54      136              5.0
55       80              0.0
56      110              0.0
57      129              2.0
58      121              6.0
59       82              3.0
60      100              3.0
61      117              1.0
62       85              4.0
63      118              4.0
64      105              1.0
65       96              4.0
66       20              3.0
67       55              2.0
68        3              3.0
69       12              3.0
70       41              2.0
71       73              2.0
72       17              5.0
73       86              1.0
74        7              0.0
75       67              2.0
76       32              2.0
77        5              2.0
78      106              3.0
79      114              2.0
80       69              0.0
81       99              2.0
82       16              0.0
83       49              2.0
84       50              2.0
85       24              1.0
86      103              3.0
87      102              0.0
88      122              1.0
89       75              1.0
90      135              0.0
91      128              2.0
92      111              1.0
93      112              1.0
94      145              3.0
95       66              3.0
96       83              3.0
97       44              2.0
98       11              2.0
99       91              2.0
100      37              4.0
101      90              0.0
102     104              2.0
103     138              2.0
104     148              2.0
105     107              1.0
106      97              5.0
107     109              2.0
108     134              1.0
109      10              2.0
110       2              0.0
111     144              0.0
112      76              0.0
113     119              2.0
114      89              1.0
115      14              0.0
116      62              1.0
117      19              1.0
118     150              2.0
119      68              0.0
120     147              1.0
121       8              1.0
122      56              4.0
123      34              0.0
124      60              5.0
125     125              0.0
126      47              1.0
127     133              0.0
128      26              2.0
129      43              1.0
130      57              0.0
131     149              1.0
132      64              0.0
133      21              0.0
134      71              1.0
135     108              2.0
136      79              0.0
137     123              0.0
138     116              0.0
139     152              0.0
140      63              0.0
141     139              3.0
142      23              1.0
143     154              0.0
144     155              0.0
145      72              0.0
146     151              0.0
147     153              5.0
148      22              0.0
149      84              0.0
150     156              0.0
151  100009              2.0
152  100022              6.0
153  100025              3.0
154  100005              1.0
155  100016              1.0
156  100015              0.0
157  100007              1.0
158  100013              4.0
159  100004              3.0
160  100012              3.0
161  100023              5.0
162  100018              1.0
163  100010              1.0
164  100002              0.0
165  100003              1.0
166  100008              1.0
167  100014              0.0
168  100021              0.0
169  100017              0.0
170  200014              0.0
171  200019              2.0
172  200002              1.0
173  200023              6.0
174  200001              3.0
175  200020              5.0
176  200022              0.0
177  200006              2.0
178  200011              3.0
179  200010              0.0
180  200015              0.0
181  200004              3.0
182  200021              3.0
183  200017              0.0
184  200008              5.0
185  200024              5.0
186  200003              0.0
187  200018              2.0
188  200009              5.0
189  200025              2.0
190  200016              1.0
191  200007              0.0
192  200005              1.0
193  200012              0.0
194  300001              0.0
195  300017              6.0
196  300015              3.0
197  300011              6.0
198  300008              3.0
199  300023              4.0
200  300021              5.0
201  300009              4.0
202  300025              3.0
203  300002              3.0
204  300012              1.0
205  300005              1.0
206  300010              1.0
207  300014              0.0
208  300016              0.0
209  300019              3.0
210  300020              1.0
211  300022              1.0
212  300013              1.0
213  300018              3.0
214  300006              0.0
215  300003              0.0
216  300004              1.0
217  300024              0.0

#### Preferences

In [24]:
# all song artist data preparation
se_data_song_artist = se_data[['artist','song']].dropna().copy()
se_data_song_artist['song'] = se_data_song_artist['song'].str.strip().str.lower()
se_data_song_artist['artist'] = se_data_song_artist['artist'].str.strip().str.lower()
se_data_song_artist['song_artist'] = se_data_song_artist['artist'] + " - " + se_data_song_artist['song']

In [25]:
song_artist_counts = se_data_song_artist['song_artist'].value_counts().reset_index().sort_values('count', ascending=False).reset_index(drop=True)
song_artist_counts['prf_top100song'] = song_artist_counts['song_artist'].isin(song_artist_counts['song_artist'][:100])
song_artist_counts['prf_top1000song'] = song_artist_counts['song_artist'].isin(song_artist_counts['song_artist'][:1000])
song_artist_counts['prf_unique_song'] = song_artist_counts['count'] == 1
print(song_artist_counts.shape)
song_artist_counts[['prf_top100song','prf_top1000song','prf_unique_song']].sum()

(65402, 5)

prf_top100song       100
prf_top1000song     1000
prf_unique_song    36095
dtype: int64

In [26]:
artist_counts = se_data_song_artist['artist'].value_counts().reset_index().sort_values('count', ascending=False).reset_index(drop=True)
artist_counts['prf_top20artist'] = artist_counts['artist'].isin(artist_counts['artist'][:20])
artist_counts['prf_top100artist'] = artist_counts['artist'].isin(artist_counts['artist'][:100])
artist_counts['prf_unique_artist'] = artist_counts['count'] == 1
print(artist_counts.shape)
artist_counts[['prf_top20artist','prf_top100artist','prf_unique_artist']].sum()

(17655, 5)

prf_top20artist        20
prf_top100artist      100
prf_unique_artist    5809
dtype: int64

In [27]:
song_artist_meta_data = se_data_song_artist.drop_duplicates()\
    .merge(artist_counts.drop(columns=['count'])).merge(song_artist_counts.drop(columns=['count']))
song_artist_meta_data

,artist,song,song_artist,prf_top20artist,prf_top100artist,prf_unique_artist,prf_top100song,prf_top1000song,prf_unique_song
0,martha tilston,rockpools,martha tilston - rockpools,False,False,False,False,False,False
1,five iron frenzy,canada,five iron frenzy - canada,False,True,False,True,True,False
2,adam lambert,time for miracles,adam lambert - time for miracles,False,False,False,False,False,False
3,enigma,knocking on forbidden doors,enigma - knocking on forbidden doors,False,False,False,False,True,False
4,daft punk,harder better faster stronger,daft punk - harder better faster stronger,True,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...
65397,tommy james and the shondells,she,tommy james and the shondells - she,False,False,False,False,False,True
65398,junior kelly,black woman,junior kelly - black woman,False,False,False,False,False,True
65399,shaggy,lucky day,shaggy - lucky day,False,False,False,False,False,True
65400,saliva,king of the stereo,saliva - king of the stereo,False,False,False,False,False,True
65401,the rolling stones,tops,the rolling stones - tops,False,False,False,False,False,True

In [28]:
se_prf_raw = se_data_sub_activity[['userId','song','artist']].dropna()\
    .assign(
        song=lambda x: x['song'].str.strip().str.lower(),
        artist=lambda x: x['artist'].str.strip().str.lower()
    )\
    .merge(song_artist_meta_data, how='left', on=['artist','song'])
se_prf_counts = se_prf_raw[['userId','song_artist']].groupby('userId').nunique().reset_index().rename(columns={'song_artist':'prf_unique_songs_count'})
se_prf_top = se_prf_raw[['userId','prf_top20artist','prf_top100artist','prf_unique_artist','prf_top100song','prf_top1000song','prf_unique_song']]\
    .groupby('userId').agg(['sum','any']).reset_index()
se_prf_top.columns = [
    '_'.join(col).rstrip('_') if isinstance(col, tuple) else col
    for col in se_prf_top.columns
]
print(se_prf_top.shape)
se_prf_top = se_prf_top.merge(se_cohort_df[['userId']], how='right', on='userId')
se_prf_top.columns = [col.replace('_sum','_count') for col in se_prf_top.columns]
any_cols = [col for col in se_prf_top.columns if col.endswith('_any')]
se_prf_top[any_cols] = se_prf_top[any_cols].fillna(False)
cnt_cols = [col for col in se_prf_top.columns if col.endswith('_count')]
se_prf_top[cnt_cols] = se_prf_top[cnt_cols].fillna(0).astype(int)
print(se_prf_top.shape)
se_prf_top

(162, 13)
(218, 13)

/var/folders/0c/_lvyy05j49g_r0hzzfhr03tm0000gn/T/ipykernel_75429/1944254836.py:18: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  se_prf_top[any_cols] = se_prf_top[any_cols].fillna(False)

,userId,prf_top20artist_count,prf_top20artist_any,prf_top100artist_count,prf_top100artist_any,prf_unique_artist_count,prf_unique_artist_any,prf_top100song_count,prf_top100song_any,prf_top1000song_count,prf_top1000song_any,prf_unique_song_count,prf_unique_song_any
0,30,23,True,56,True,12,True,18,True,60,True,35,True
1,9,17,True,43,True,0,False,19,True,45,True,14,True
2,74,0,False,0,False,0,False,0,False,0,False,0,False
3,54,50,True,122,True,20,True,52,True,151,True,99,True
4,4,46,True,100,True,11,True,50,True,130,True,73,True
5,101,73,True,183,True,21,True,84,True,240,True,149,True
6,78,0,False,0,False,0,False,0,False,0,False,0,False
7,88,23,True,56,True,3,True,24,True,57,True,26,True
8,95,2,True,12,True,1,True,5,True,13,True,14,True
9,25,51,True,116,True,10,True,51,True,138,True,77,True
10,142,54,True,131,True,14,True,68,True,164,True,79,True
11,13,12,True,38,True,1,True,15,True,34,True,26,True
12,45,1,True,1,True,0,False,2,True,5,True,2,True
13,39,84,True,216,True,26,True,103,True,249,True,167,True
14,87,26,True,51,True,4,True,23,True,63,True,32,True
15,28,82,True,192,True,25,True,88,True,248,True,154,True
16,131,7,True,13,True,1,True,9,True,18,True,12,True
17,126,12,True,32,True,2,True,14,True,41,True,31,True
18,146,1,True,4,True,1,True,2,True,8,True,4,True
19,59,2,True,9,True,3,True,2,True,10,True,13,True
20,15,8,True,28,True,8,True,15,True,38,True,39,True
21,36,7,True,21,True,4,True,10,True,25,True,20,True
22,120,39,True,92,True,12,True,38,True,105,True,58,True
23,92,79,True,217,True,28,True,94,True,257,True,142,True
24,33,15,True,51,True,3,True,20,True,53,True,26,True
25,51,75,True,188,True,24,True,89,True,233,True,116,True
26,27,0,False,0,False,0,False,0,False,0,False,0,False
27,143,4,True,8,True,1,True,5,True,6,True,4,True
28,140,65,True,165,True,19,True,81,True,202,True,107,True
29,6,14,True,36,True,2,True,14,True,36,True,26,True
30,124,22,True,59,True,6,True,27,True,61,True,33,True
31,141,5,True,11,True,3,True,5,True,16,True,16,True
32,93,3,True,4,True,0,False,0,False,6,True,1,True
33,81,0,False,0,False,0,False,0,False,1,True,0,False
34,40,6,True,15,True,4,True,6,True,17,True,16,True
35,94,0,False,0,False,0,False,0,False,0,False,0,False
36,113,10,True,30,True,2,True,13,True,33,True,19,True
37,98,9,True,37,True,7,True,21,True,46,True,23,True
38,137,0,False,0,False,0,False,0,False,0,False,0,False
39,65,20,True,51,True,6,True,28,True,71,True,27,True
40,53,50,True,122,True,13,True,56,True,140,True,75,True
41,42,25,True,51,True,9,True,28,True,66,True,31,True
42,115,82,True,209,True,16,True,82,True,232,True,145,True
43,38,3,True,8,True,2,True,6,True,10,True,12,True
44,58,98,True,227,True,26,True,114,True,280,True,151,True
45,77,22,True,39,True,3,True,24,True,53,True,32,True
46,52,39,True,86,True,8,True,35,True,85,True,46,True
47,29,16,True,40,True,2,True,19,True,50,True,27,True
48,70,24,True,43,True,1,True,23,True,60,True,23,True
49,61,57,True,127,True,9,True,61,True,161,True,79,True
50,46,16,True,38,True,5,True,19,True,46,True,23,True
51,35,33,True,76,True,11,True,36,True,89,True,60,True
52,132,5,True,15,True,4,True,10,True,23,True,12,True
53,127,0,False,0,False,0,False,0,False,0,False,0,False
54,136,50,True,134,True,19,True,59,True,172,True,113,True
55,80,0,False,0,False,0,False,0,False,0,False,0,False
56,110,0,False,0,False,0,False,0,False,0,False,0,False
57,129,10,True,28,True,3,True,12,True,27,True,29,True
58,121,38,True,91,True,12,True,39,True,103,True,68,True
59,82,9,True,34,True,0,False,11,True,39,True,16,True
60,100,4,True,7,True,2,True,4,True,9,True,6,True
61,117,3,True,5,True,0,False,3,True,9,True,4,True
62,85,29,True,65,True,3,True,25,True,66,True,58,True
63,118,6,True,28,True,3,True,5,True,31,True,18,True
64,105,3,True,11,True,1,True,4,True,17,True,12,True
65,96,15,True,28,True,2,True,15,True,32,True,25,True
66,20,7,True,17,True,2,True,5,True,17,True,14,True
67,55,3,True,6,True,1,True,4,True,6,True,2,True
68,3,10,True,24,True,4,True,15,True,45,True,24,True
69,12,24,True,59,True,11,True,33,True,86,True,50,True
70,41,6,True,24,True,5,True,11,True,29,True,12,True
71,73,13,True,28,True,6,True,10,True,36,True,39,True
72,17,42,True,144,True,18,True,57,True,162,True,119,True
73,86,0,False,1,True,0,False,1,True,2,True,2,True
74,7,0,False,0,False,0,False,0,False,0,False,0,False
75,67,3,True,20,True,2,True,4,True,20,True,17,True
76,32,2,True,8,True,1,True,5,True,10,True,7,True
77,5,2,True,10,True,0,False,5,True,11,True,2,True
78,106,27,True,59,True,7,True,30,True,68,True,47,True
79,114,5,True,12,True,1,True,7,True,14,True,4,True
80,69,0,False,0,False,0,False,0,False,0,False,0,False
81,99,4,True,6,True,1,True,3,True,7,True,5,True
82,16,0,False,0,False,0,False,0,False,0,False,0,False
83,49,3,True,8,True,0,False,1,True,6,True,6,True
84,50,8,True,15,True,3,True,8,True,20,True,8,True
85,24,4,True,15,True,2,True,5,True,18,True,13,True
86,103,35,True,82,True,8,True,41,True,100,True,65,True
87,102,0,False,0,False,0,False,0,False,0,False,0,False
88,122,0,False,2,True,0,False,1,True,3,True,0,False
89,75,4,True,8,True,1,True,3,True,12,True,8,True
90,135,0,False,0,False,0,False,0,False,0,False,0,False
91,128,16,True,37,True,3,True,21,True,40,True,26,True
92,111,14,True,33,True,6,True,18,True,46,True,19,True
93,112,1,True,7,True,0,False,1,True,7,True,4,True
94,145,11,True,23,True,3,True,14,True,21,True,15,True
95,66,15,True,29,True,2,True,16,True,32,True,19,True
96,83,2,True,4,True,0,False,2,True,5,True,3,True
97,44,32,True,76,True,15,True,43,True,90,True,60,True
98,11,3,True,11,True,2,True,4,True,13,True,7,True
99,91,17,True,53,True,3,True,28,True,63,True,32,True
100,37,32,True,69,True,10,True,42,True,86,True,52,True
101,90,0,False,0,False,0,False,0,False,0,False,0,False
102,104,14,True,28,True,3,True,13,True,30,True,12,True
103,138,18,True,51,True,7,True,19,True,48,True,29,True
104,148,15,True,38,True,5,True,17,True,55,True,32,True
105,107,0,False,5,True,0,False,0,False,5,True,1,True
106,97,48,True,134,True,17,True,50,True,149,True,78,True
107,109,12,True,38,True,4,True,14,True,49,True,28,True
108,134,0,False,2,True,1,True,0,False,1,True,2,True
109,10,6,True,21,True,2,True,10,True,23,True,13,True
110,2,0,False,0,False,0,False,0,False,0,False,0,False
111,144,0,False,0,False,0,False,0,False,0,False,0,False
112,76,0,False,0,False,0,False,0,False,0,False,0,False
113,119,3,True,8,True,1,True,3,True,17,True,7,True
114,89,0,False,2,True,0,False,2,True,3,True,1,True
115,14,0,False,0,False,0,False,0,False,0,False,0,False
116,62,10,True,34,True,6,True,18,True,49,True,21,True
117,19,8,True,27,True,1,True,14,True,39,True,13,True
118,150,6,True,19,True,3,True,8,True,22,True,14,True
119,68,0,False,0,False,0,False,0,False,0,False,0,False
120,147,5,True,13,True,3,True,5,True,12,True,11,True
121,8,11,True,25,True,3,True,11,True,30,True,26,True
122,56,11,True,23,True,2,True,14,True,31,True,13,True
123,34,0,False,0,False,0,False,0,False,0,False,0,False
124,60,24,True,59,True,2,True,29,True,69,True,34,True
125,125,0,False,0,False,0,False,0,False,0,False,0,False
126,47,0,False,0,False,0,False,1,True,2,True,0,False
127,133,0,False,0,False,0,False,0,False,0,False,0,False
128,26,11,True,26,True,1,True,12,True,33,True,16,True
129,43,1,True,3,True,0,False,1,True,4,True,4,True
130,57,0,False,0,False,0,False,0,False,0,False,0,False
131,149,3,True,4,True,1,True,4,True,7,True,8,True
132,64,0,False,0,False,0,False,0,False,0,False,0,False
133,21,0,False,0,False,0,False,0,False,0,False,0,False
134,71,1,True,1,True,0,False,2,True,2,True,0,False
135,108,27,True,73,True,7,True,26,True,83,True,41,True
136,79,0,False,0,False,0,False,0,False,0,False,0,False
137,123,0,False,0,False,0,False,0,False,0,False,0,False
138,116,0,False,0,False,0,False,0,False,0,False,0,False
139,152,0,False,0,False,0,False,0,False,0,False,0,False
140,63,0,False,0,False,0,False,0,False,0,False,0,False
141,139,23,True,60,True,7,True,34,True,80,True,44,True
142,23,2,True,7,True,0,False,6,True,12,True,8,True
143,154,0,False,0,False,0,False,0,False,0,False,0,False
144,155,0,False,0,False,0,False,0,False,0,False,0,False
145,72,0,False,0,False,0,False,0,False,0,False,0,False
146,151,0,False,0,False,0,False,0,False,0,False,0,False
147,153,13,True,45,True,4,True,17,True,48,True,31,True
148,22,0,False,0,False,0,False,0,False,0,False,0,False
149,84,0,False,0,False,0,False,0,False,0,False,0,False
150,156,0,False,0,False,0,False,0,False,0,False,0,False
151,100009,10,True,30,True,4,True,14,True,35,True,29,True
152,100022,9,True,27,True,2,True,12,True,45,True,13,True
153,100025,34,True,83,True,4,True,36,True,91,True,44,True
154,100005,0,False,4,True,1,True,3,True,8,True,4,True
155,100016,1,True,2,True,2,True,1,True,6,True,5,True
156,100015,0,False,0,False,0,False,0,False,0,False,0,False
157,100007,0,False,3,True,0,False,0,False,1,True,1,True
158,100013,20,True,68,True,9,True,33,True,76,True,33,True
159,100004,7,True,16,True,1,True,10,True,18,True,11,True
160,100012,10,True,29,True,2,True,9,True,39,True,17,True
161,100023,30,True,71,True,12,True,27,True,78,True,40,True
162,100018,1,True,3,True,0,False,2,True,4,True,1,True
163,100010,4,True,11,True,2,True,5,True,8,True,10,True
164,100002,0,False,0,False,0,False,0,False,0,False,0,False
165,100003,0,False,2,True,0,False,0,False,0,False,0,False
166,100008,2,True,4,True,1,True,1,True,4,True,7,True
167,100014,0,False,0,False,0,False,0,False,0,False,0,False
168,100021,0,False,0,False,0,False,0,False,0,False,0,False
169,100017,0,False,0,False,0,False,0,False,0,False,0,False
170,200014,0,False,0,False,0,False,0,False,0,False,0,False
171,200019,7,True,15,True,2,True,6,True,18,True,15,True
172,200002,1,True,2,True,2,True,1,True,4,True,5,True
173,200023,16,True,44,True,6,True,20,True,38,True,27,True
174,200001,6,True,22,True,2,True,7,True,21,True,5,True
175,200020,6,True,26,True,2,True,10,True,36,True,19,True
176,200022,0,False,0,False,0,False,0,False,0,False,0,False
177,200006,1,True,1,True,0,False,0,False,2,True,3,True
178,200011,16,True,41,True,10,True,22,True,56,True,31,True
179,200010,0,False,0,False,0,False,0,False,0,False,0,False
180,200015,0,False,0,False,0,False,0,False,0,False,0,False
181,200004,15,True,37,True,3,True,20,True,54,True,23,True
182,200021,22,True,52,True,14,True,27,True,68,True,43,True
183,200017,0,False,0,False,0,False,0,False,0,False,0,False
184,200008,44,True,112,True,8,True,43,True,123,True,63,True
185,200024,15,True,51,True,3,True,21,True,53,True,37,True
186,200003,0,False,0,False,0,False,0,False,0,False,0,False
187,200018,12,True,33,True,2,True,9,True,41,True,21,True
188,200009,55,True,111,True,12,True,47,True,116,True,72,True
189,200025,2,True,13,True,1,True,4,True,11,True,4,True
190,200016,0,False,1,True,1,True,1,True,3,True,4,True
191,200007,0,False,0,False,0,False,0,False,0,False,0,False
192,200005,3,True,4,True,0,False,2,True,3,True,4,True
193,200012,0,False,0,False,0,False,0,False,0,False,0,False
194,300001,0,False,0,False,0,False,0,False,0,False,0,False
195,300017,33,True,73,True,6,True,29,True,91,True,58,True
196,300015,15,True,39,True,1,True,17,True,47,True,24,True
197,300011,47,True,145,True,18,True,60,True,182,True,123,True
198,300008,9,True,31,True,1,True,17,True,37,True,14,True
199,300023,30,True,86,True,12,True,48,True,125,True,83,True
200,300021,44,True,106,True,15,True,45,True,127,True,86,True
201,300009,40,True,120,True,21,True,55,True,152,True,89,True
202,300025,8,True,23,True,3,True,12,True,31,True,22,True
203,300002,34,True,71,True,4,True,33,True,88,True,44,True
204,300012,2,True,7,True,0,False,3,True,8,True,1,True
205,300005,5,True,10,True,3,True,2,True,9,True,6,True
206,300010,2,True,5,True,0,False,3,True,3,True,2,True
207,300014,0,False,0,False,0,False,0,False,0,False,0,False
208,300016,0,False,0,False,0,False,0,False,0,False,0,False
209,300019,42,True,101,True,17,True,47,True,134,True,74,True
210,300020,3,True,10,True,0,False,4,True,12,True,3,True
211,300022,0,False,1,True,0,False,2,True,3,True,3,True
212,300013,4,True,8,True,2,True,6,True,15,True,13,True
213,300018,4,True,7,True,0,False,6,True,11,True,8,True
214,300006,0,False,0,False,0,False,0,False,0,False,0,False
215,300003,0,False,0,False,0,False,0,False,0,False,0,False
216,300004,10,True,17,True,2,True,8,True,22,True,9,True
217,300024,0,False,0,False,0,False,0,False,0,False,0,False

#### Merge All Features

In [29]:
print(f"Persona shape: {se_persona.shape}")
print(f"Last level shape: {se_last_level.shape}")
print(f"Page shape: {se_page.shape}")
print(f"Session shape: {se_session.shape}")
print(f"Days active shape: {se_days_active.shape}")
print(f"Preference shape: {se_prf_top.shape}")

in_scope_user_ids = se_cohort_df['userId'].unique()
active_user_ids = se_data_sub_activity['userId'].unique()
print(f"Total in-scope users: {len(in_scope_user_ids)}")
print(f"Total active users in filtered period: {len(active_user_ids)}")
print(f"""Persona, all in-scope users found: {sum(se_persona['userId'].isin(in_scope_user_ids)) == len(in_scope_user_ids)}, 
      all active users found: {sum(se_persona['userId'].isin(active_user_ids)) == len(active_user_ids)} """)
print(f"""Last level, all in-scope users found: {sum(se_last_level['userId'].isin(in_scope_user_ids)) == len(in_scope_user_ids)}, 
      all active users found: {sum(se_last_level['userId'].isin(active_user_ids)) == len(active_user_ids)} """)
print(f"""Page, all in-scope users found: {sum(se_page['userId'].isin(in_scope_user_ids)) == len(in_scope_user_ids)}, 
      all active users found: {sum(se_page['userId'].isin(active_user_ids)) == len(active_user_ids)} """)
print(f"""Session, all in-scope users found: {sum(se_session['userId'].isin(in_scope_user_ids)) == len(in_scope_user_ids)}, 
      all active users found: {sum(se_session['userId'].isin(active_user_ids)) == len(active_user_ids)} """)
print(f"""Days active, all in-scope users found: {sum(se_days_active['userId'].isin(in_scope_user_ids)) == len(in_scope_user_ids)}, 
      all active users found: {sum(se_days_active['userId'].isin(active_user_ids)) == len(active_user_ids)} """)
print(f"""Preference, all in-scope users found: {sum(se_prf_top['userId'].isin(in_scope_user_ids)) == len(in_scope_user_ids)}, 
      all active users found: {sum(se_prf_top['userId'].isin(active_user_ids)) == len(active_user_ids)} """)

Persona shape: (218, 7)
Last level shape: (218, 3)
Page shape: (218, 20)
Session shape: (218, 3)
Days active shape: (218, 2)
Preference shape: (218, 13)
Total in-scope users: 218
Total active users in filtered period: 163
Persona, all in-scope users found: True,
      all active users found: True
Last level, all in-scope users found: True,
      all active users found: True
Page, all in-scope users found: True,
      all active users found: True
Session, all in-scope users found: True,
      all active users found: True
Days active, all in-scope users found: True,
      all active users found: True
Preference, all in-scope users found: True,
      all active users found: True

In [30]:
print(f"Cohort df shape: {se_cohort_df.columns.tolist()}")
print(f"Persona shape: {se_persona.columns.tolist()}")
print(f"Last level shape: {se_last_level.columns.tolist()}")
print(f"Page shape: {se_page.columns.tolist()}")
print(f"Session shape: {se_session.columns.tolist()}")
print(f"Days active shape: {se_days_active.columns.tolist()}")
print(f"Preference shape: {se_prf_top.columns.tolist()}")

Cohort df shape: ['userId', 'cancel_date', 'churn', 'start_date', 'end_date', 'has_activity']
Persona shape: ['userId', 'psn_gender', 'psn_city', 'psn_state', 'acct_day_since_reg', 'psn_multi_city', 'psn_multi_state']
Last level shape: ['userId', 'acct_last_level', 'acct_multiple_levels']
Page shape: ['userId', 'act_page_about', 'act_page_add_friend', 'act_page_add_to_playlist', 'act_page_downgrade', 'act_page_error', 'act_page_help', 'act_page_home', 'act_page_logout', 'act_page_nextsong', 'act_page_roll_advert', 'act_page_save_settings', 'act_page_settings', 'act_page_submit_downgrade', 'act_page_submit_upgrade', 'act_page_thumbs_down', 'act_page_thumbs_up', 'act_page_upgrade', 'total_page_visits', 'unique_page_types']
Session shape: ['userId', 'session_count', 'session_avg_pages']
Days active shape: ['userId', 'act_days_active']
Preference shape: ['userId', 'prf_top20artist_count', 'prf_top20artist_any', 'prf_top100artist_count', 'prf_top100artist_any', 'prf_unique_artist_count', 'prf_unique_artist_any', 'prf_top100song_count', 'prf_top100song_any', 'prf_top1000song_count', 'prf_top1000song_any', 'prf_unique_song_count', 'prf_unique_song_any']

In [31]:
se_data_processed = se_cohort_df\
    .merge(se_persona, how='left', on='userId')\
    .merge(se_last_level, how='left', on='userId')\
    .merge(se_page, how='left', on='userId')\
    .merge(se_session, how='left', on='userId')\
    .merge(se_days_active, how='left', on='userId')\
    .merge(se_prf_top, how='left', on='userId')

print(f"Final processed data shape: {se_data_processed.shape}")
print(f"Users with Activities: {(se_data_processed['has_activity']).sum()}, inactive users: {se_data_processed.shape[0] - (se_data_processed['has_activity']).sum()}")
print(f"Churned users: {se_data_processed['churn'].sum()}, non-churned users: {se_data_processed.shape[0] - se_data_processed['churn'].sum()}")
se_data_processed.to_csv("../Output/data_proc_eng/se_data_processed_pd.csv", index=False,encoding='utf-8')

Final processed data shape: (218, 48)
Users with Activities: 163, inactive users: 55
Churned users: 45, non-churned users: 173